FROM python:3.9-slim-buster
WORKDIR /app
COPY requirements.txt requirements.txt
COPY home_price_model.pth home_price_model.pth
RUN pip install -r requirements.txt
COPY . .
EXPOSE 80
CMD ["python", "app.py"]
